logging
Signed-off-by: Chris Lyons <52037738+mephmanx@users.noreply.github.com>

diff --git a/manifests/k8s-kafka.yaml b/manifests/k8s-kafka.yaml
--- a/manifests/k8s-kafka.yaml
+++ b/manifests/k8s-kafka.yaml
@@ -354,7 +354,11 @@ spec:
               env | grep SCHEMA_REGISTRY;
               echo "Contents of /etc/confluent/docker/run:";
               cat /etc/confluent/docker/run;
-              /etc/confluent/docker/run;
+              echo "Running preflight checks...";
+              /etc/confluent/docker/ensure || { echo "Preflight checks failed"; exit 1; };
+              echo "Preflight checks completed successfully.";
+              echo "Launching Schema Registry...";
+              /etc/confluent/docker/launch || { echo "Launch failed"; exit 1; };
           env:
             - name: SCHEMA_REGISTRY_LISTENERS
               value: "http://0.0.0.0:8081"
